### PR TITLE
Fix partial Workspaces export

### PR DESCRIPTION
**Pull request by druckgott**
Workspace Export now works. It's only one line to fix it.

Also, an example export:
[workspaces.json](https://github.com/iNavFlight/blackbox-log-viewer/files/14922818/workspaces.json)

**Currently there is one problem on the beginning you have to insert: `{graphConfig : [` and on the end `]}`
And then ZIP the file.**

You can also manually do it until the new version is coming out:

```
got to main.js

search for:

            workspaceGraphConfigs = {graphConfig : [
                                    null,null,null,null,null,null,null,null,null,null
                                    ]};
                                    
replace with

workspaceGraphConfigs = graphConfig;
```

### CODE REVIEW

**Comment by Tonynux** [comment]
Hi. This is my update in main.js :

>     // New workspaces feature; local storage of user configurations
>     prefs.get('workspaceGraphConfigs', function(item) {
>         if(item) {
>             workspaceGraphConfigs = item;
>             } else {
>             //workspaceGraphConfigs = {graphConfig : [
>             //                        null,null,null,null,null,null,null,null,null,null
>             //                        ]};
>             //Tony
> 	    workspaceGraphConfigs = graphConfig;
>             }
>     });
> 
>     // Get the offsetCache buffer

Now I created my Graphs:

Graph
Legend

Then trying to export. And this is my JSON file:

json

Just one field exported.

**Comment by druckgott** [comment]
Please try to press Ctrl z 2 Times and test it again please.

**Comment by Tonynux** [comment]
Pressed Ctrl z 2 times (before exporting workspace), but... same result: one field exported.

**Comment by druckgott** [comment]
Mhh. Very Strange i think there is a bigger Bug inside.

**Comment by mmosca** [comment]
Can you update to the latest master, so it runs the ci build?

**Comment by druckgott** [comment]
Done

**Pull request closed without merging**
