### PR TITLE
Add GPS data option + other improvements

### PR DESCRIPTION
**Pull request by breadoven**
Adds option to include GPS data output.

Also adds Home Distance field and generally improves formatting of data fields.

### CODE REVIEW

**Comment by mmosca** [comment]
Can you update to the latest master, so it runs the ci build?

**Comment by breadoven** [comment]
I can update to the master but I've noticed the spectrum analyser doesn't show any frequencies, just infinity, so I need to check what's wrong there because it works with the current master. Maybe it just needs updating from the master ... not sure.

**Comment by breadoven** [comment]
OK seems to work properly after updating from master.

**Comment by mmosca** [comment]
That was fixed by #105

Do you have any log files I can use to test this?

**Comment by breadoven** [comment]
> That was fixed by #105
> 
> Do you have any log files I can use to test this?

It should work with any log file that includes GPS.

**Pull request merged**
